### ISSUE TITLE
Wallet balance summary is displayed with E notation for small amounts 

### ISSUE THREAD

**Issue by baptistemesta** [Meeds-io/wallet#181]
Hello!

When very few meeds is present inside a wallet, the balance is shown using the E notation. See screenshot below

![Screenshot 2022-02-02 at 10 18 37](https://user-images.githubusercontent.com/2739234/152126457-0b041790-d084-46a4-8769-cd935dff8528.png)

I would have expected either to have `0` display or `0+` 
In any case it break the alignment with the number of order.

![Screenshot 2022-02-02 at 10 23 35](https://user-images.githubusercontent.com/2739234/152126750-66ecb8d9-a9c2-4ab3-8e0e-10706055f695.png)

Regards,

**Comment by boubaker** [comment]
Should be fixed by https://github.com/Meeds-io/wallet/pull/182 and https://github.com/Meeds-io/platform-ui/pull/368
